language: node_js
node_js:
  - 'node'
services:
  - mongodb
env:
  global:
    - MONGODB_URL="mongo://travis:test@localhost:27017"
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
cache:
  directories:
    - node_modules
    - bower_components
